# API 키 설정
# Sapling API 키 설정 - https://sapling.ai에서 발급받을 수 있습니다
SAPLING_API_KEY = "9PUFHEZ3FVY6MIWPXMOXDR0S3G6ZW1RD"

# GrammarBot API 키 설정 - https://www.grammarbot.io에서 발급받을 수 있습니다
GRAMMARBOT_API_KEY = "KS9C5N3Y"

# 기타 설정
DEBUG = false 